name: Prefixes
version: 1.1
main: app.simplecloud.plugin.prefixes.paper.PrefixesPlugin
api-version: 1.21.4
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      require: true
    CustomNames:
      load: BEFORE
      require: true
      join-classpath: true
authors:
  - dayyeeet